title: Nicolas Lequeux | Full-stack web developper
author: Nicolas Lequeux
email: contact@nicolaslequeux.com
description: Full Stack Developper

show_excerpts: false # set to true to show excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
