title: Nicolas Lequeux - Full-Stack Web Developer
author: Nicolas Lequeux
email: contact@nicolaslequeux.com
description: Nicolas Lequeux - I am a freelance full-stack web developer
url: http://www.nicolaslequeux.com
type: website

# Provide a default OGP image to all posts and pages.
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og-img-header.png

# Set to true to show excerpts on the homepage
show_excerpts: false

# Google Analytics
# google_analytics: UA-150681617-1

# seo gem
social:
  name: Nicolas Lequeux
  links:
    - https://www.linkedin.com/in/nicolas-lequeux-5b02806/
    - https://github.com/nicolaslequeux

# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
